name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 24
          components: native-image
          cache: maven

      - name: Setup Maven
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin
          cache: maven

      - name: Build
        run: mvn -Pnative -DskipTests

      - name: Dist
        run: mvn -Pdist -DskipTests

      - name: Relese
        run: mvn jreleaser:release -Djreleaser.select.current.platform -DskipTests
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
