name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04-arm', 'windows-latest', 'macos-latest']
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 24
          cache: maven

      - uses: actions/cache@v4.2.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Setup Maven
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Build
        run: mvn -Pnative -DskipTests

      - name: Dist
        run: mvn -Pdist -DskipTests

      - name: Release
        run: mvn jreleaser:release -D"jreleaser.select.current.platform" -DskipTests
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
